### ISSUE TITLE
Practica 3

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/practica-6-relaciones-funciones-y-plano-cartesiano-equipo-alan-ivan#1]
[Practica 3 Practica en plano cartesiano.pdf](https://github.com/user-attachments/files/17164625/Practica.3.Practica.en.plano.cartesiano.pdf)

**Comment by Fidel20-01** [comment]
Portada:22/25
Procedimiento:16/25
Figuras, ilustraciones y fotografías:17/25
Resultados y conclusiones:20/25
75/100
Calificación: 15/20
Nota: 
-Portada: Nombre del Profesor, lugar y fecha confusa.
-Procedimiento: Lista de figuras, obtención de datos no explicada (arco tangente, pendiente, etc.),objetivo confuso.
-Figuras, ilustraciones y fotografías: lista de figuras faltante, las imágenes colocadas eran pocas.
-Resultados y conclusiones: Conclusión de 8 lineas.
Evaluó: Equipo de Juan Pablo C.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
